services:
  hero-mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: hero-mailhog
    restart: unless-stopped
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - hero_net
  hero-redis-commander:
    image: 'rediscommander/redis-commander:latest'
    container_name: hero-redis-commander
    restart: unless-stopped
    environment:
      - 'REDIS_HOSTS=local:hero-redis:6379'
    ports:
      - '8081:8081'
    networks:
      - hero_net
  hero-adminer:
    image: 'adminer:latest'
    container_name: hero-adminer
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=hero-db
    ports:
      - '8080:8080'
    depends_on:
      - hero-db
    networks:
      - hero_net
  hero-meili:
    image: 'getmeili/meilisearch:v1.7'
    container_name: hero-meili
    restart: unless-stopped
    environment:
      - MEILI_NO_ANALYTICS=true
    ports:
      - '7700:7700'
    volumes:
      - 'meili_data:/meili_data'
    networks:
      - hero_net
  hero-minio:
    image: 'minio/minio:latest'
    container_name: hero-minio
    restart: unless-stopped
    command:
      - server
      - /data
      - '--console-address'
      - ':9001'
    environment:
      - 'MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}'
      - 'MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    networks:
      - hero_net
  hero-phpmyadmin:
    image: 'phpmyadmin:latest'
    container_name: hero-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=hero-db
      - PMA_PORT=3306
    ports:
      - '8082:80'
    depends_on:
      - hero-db
    networks:
      - hero_net
  hero-db:
    env_file:
      - ./api/.env
    environment:
      MYSQL_DATABASE: '$${DB_DATABASE}'
      MYSQL_USER: '$${DB_USERNAME}'
      MYSQL_PASSWORD: '$${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '$${DB_ROOT_PASSWORD:-root}'
volumes:
  meili_data: null
  minio_data: null
