<p>Ou seja, das nossas ideias, uma parte aparecerá em público, mas a origem e o que nós combinamos entre nós jamais será sabido. Vocês imaginam porque, na formação da Royal Society inglês, só hoje começa a aparecer recentemente, mas mesmo assim ele não sabe a história inteira? Porque se você imaginar como uma sociedade secreta guarda um segredo, esconde o segredo e não conta para os outros, mas lá dentro o pessoal tá sabendo, você está muitíssimo enganado.</p>
<p>Ele mostra que uma grande parte da atividade dos primeiros historiadores maçônicos foi disfarçar a história da Maçonaria e inventar histórias imaginárias, e repassaram os próprios membros da Maçonaria de quatro séculos. Tem que chegar um mestre. Espera aí, eu tô aqui ficando louco, porque essa história da Maçonaria eu não tô entendendo mais nada. É então ele sabe que a Maçonaria do século XVII participou de certas operações importantes, a criação do site que criou a imagem, vamos dizer, da mentalidade científica moderna, e que ao mesmo tempo, todos aqueles que estão participando disso por trás eram alquimistas, astrólogos, praticantes de magia, etc. Então você tem um conjunto de crenças absolutamente irracionais que a própria ciência vai rejeitar criando a imagem da ciência que rejeita, e depois colocando em cima disso, camadas e camadas de camada de camada de desinformação e disfarce, ao ponto de criar uma massa inextricável de dados.</p>

<p>Então é claro que se você não sabe que não conhece a história da mansão Maria moderna você não vai entender nada da história da origem da ciência moderna da mentalidade moderna etc etc mas se dentro da própria maçonaria os seus próprios historiadores estão mentindo para os outros</p>
<p>Então a história das luzes de repente nós escapamos das Trevas da antiguidade tudo se fez luz como como se chegou a pensar Nilton lançou a luz sobre toda a Constituição do universo de quem mais quem era Newton da onde ele veio a história de Newton é pior que a história do Barack Obama é tudo disfarçado é mentira em cima de mentira em cima de mim</p>
<p>Então qual é o sentido então da obra de Newton hoje nós entendemos que a toda a teoria da gravitação universal para era parte de uma teologia que ele estava construindo mais ou menos uma teologia de tipo islâmico que ele pretendia substituir não que ele tivesse influência islâmica mas era o mesmo esquema de pensamento a unidade absoluta ele pretendia então impor em lugar da Trindade e isso por sua vez baseado em estudos né que ele fez de numerologia de Alquimia etc etc e bom então se entendemos somente a lei da gravitação universal separada disso ela tem um sentido mas o fato dela nunca teve separado ela só entende separada na mentalidade das relações seguintes as quais não foi contada a história inteira</p>

<p>Então isso quer dizer que uma das obrigações que incumbem contra esta geração de estudiosos não é esclarecer tudo mas jamais esclareceremos tudo isto é uma massa de disfarce camuflagem mas a primeira obrigação é entender que as luzes não existem não existe uma passagem das Trevas para a luz não existe o império Universal da Luz como queria um todo mundo vai saber tudo e tudo está esclarecido nós estamos dizemos a Deus as trevas da antiguidade onde as pessoas eram conduzidas por fatores misteriosos na mão dos fatores misteriosos</p>
<p>Então mas eu acredito que uma das umas outras obrigações apresentação de estudiosos Tá certo deste elemento de segredo de mistificação que existe por trás de todas todas as forças históricas porém cuja presença no cenário se torna cada vez mais intensa a medida que o tempo passa desde a origem da chamada modernidade então a presença do elemento secreto na sociedade ela se torna possível graças a evolução da tecnologia não é isso quando dizemos assim a ciência técnica aumentaram o poder do Homem Sobre a Natureza digo do homem que homem é esse não aumentar o poder de uns homens sobre outros homens e na mesma medida aumenta a distância e aquilo que lhe parece ser uma democratização no sentido é uma eletrização em outros isso aí é absolutamente inevitável fazer</p>

<p>Qualquer instrumento técnico que você inventa e qualquer um coloca certas possibilidades da mão na nas mãos de umas pessoas e evidentemente aumenta o poder dela sobre as outras pessoas não sobre a natureza dizer que o homem tem poder sobre a natureza é se refazer o homem tem poder da humanidade das ações materiais que a humanidade pode empreender desde o início dos tempos até hoje você vê que mal arranhou a superfície de um planeta E o restante do universo A Hiper ficou perfeitamente em diferentes As Nossas ações né No que que as nossas ações mudam a conduta das galáxias absolutamente nada então quando você fala natureza mesmo sentido físico então você pode dizer aumentou um pouquinho o poder de algumas pessoas sobre o ambiente imediato porém aumentou muito mais o poder dessas pessoas sobre outras pessoas</p>
<p>Então a associação da técnica com a democratização é um dos grandes mitos que nós temos que tirar da nossa cabeça se a técnica confere poder de ação é em primeiro lugar poder de ação sobre outras pessoas não é isso e só muito secundariamente sobre aspas à natureza costumam fragmento infinitesimal da natureza você imagina por exemplo Os projetos que existem hoje de controle do clima quantas pessoas se dedicam a isso mas a ação desses alguns milhares vai afetar a vida de bilhões de pessoas que jamais vão saber Jamais vão entender o</p>

<p>que é que eles estão fazendo a ideia por exemplo do All gore de que as ações humanas estão modificando o ambiente cósmico inteiro e de que portanto nós através de uma certa organização da sociedade nós podemos Vamos vamos racionalizar e controlar esta ação quer dizer nós estamos exercendo uma ação destrutiva porque a nossa ações são anárquicas mas se organizamos tudo então teremos uma ação planejada e racional sobre o planeta você imagina que que o planejamento do ambiente Ecológico a terra na qual você vive já não vai ser uma doação de doação da natureza mas é a propriedade do Má administração planetária que determina então o que você pode produzir o que você pode comer né quanto você Pode respirar e assim por diante</p>
<p>então isso quer dizer que no fim de dois séculos de evolução democrática entre aspas nós temos hoje vamos fazer um Panorama de uma eletrização monstruosa que permanece secreta a maior parte das pessoas Então quanto mais pessoas acreditam que estão vivendo no mundo de liberdade democracia etc mas elas são poderes um planejamento tecnológico que cura a compreensão de escapa completamente Qual é a nossa obrigação de tentar entender isto nós não vamos conseguir decifrar o processo histórico mas aquilo que está o nosso alcance entender dentro do Panorama imediato e dentro da história dos dois ou três últimos séculos não quer dizer que para você vai ficar tudo Claro porque muitas ações humanas emergem de um abismo de loucura e de maldade que nós não podemos as vezes</p>

<p>Fica difícil de imaginar, mas quando você identifica essa origem, isto aqui tem uma origem abissal. Tem um elemento Demoníaco você sabe que, você não vai entender, porque não tem explicação, mas o entender é somente uma parte do Saber e do conjunto que você sabe só uma parte, você vai entender e você tem que admitir com incompreensível e que você tem que aceitar como realidade mesmo quando não possa compreender. Isso aqui para mim se tornou uma regra da vida intelectual, admitir a existência dos fatos que eu não compreendo.</p>
<p>Se você vai admite isso então é o seguinte, você só admite um fato quando você já tem explicação para ele. Isso quer dizer que o seu cérebro se fechou dando uma explicação para existente e o que quer que sai fora da explicação você vai negar. Se você quer saber, a negação do fato incompreensivo se tornou quase uma cláusula pétrea do debate Acadêmico contemporâneo. Porque aquilo que é considerado compreensível é aquilo que é aceito pelo consenso da classe falante, aquilo que eles dizem merece respeito, atenção e os outros dizem não tem a mínima importância. Portanto o que quer que venha daí para dentro só será aceito se passar pelo crivo destas pessoas, ou seja, os fatos novos só serão admitidos se nós, o Consenso da classe acadêmica, já tivemos explicação prévia para eles. Então isso aí é um anti-conhecimento, esse é o obscurantismo mais extremo que você pode imaginar como resultado de dois ou três séculos de Império das luzes.</p>
<p>Tá certo então isso quer dizer que no nosso estudo de história das ideias, história da filosofia, jamais fugiremos dos elementos.</p>

<p>Secretivos, irracionais, demoníacos, etc., por que isso faz parte da estrutura da realidade. Então vamos retomar aqui. E esse tem algum ponto que a gente ia comentar.</p>
<p>Ah, eu queria lembrar uma coisa para vocês. Quando a gente tá falando esse negócio, a função da Maçonaria no começo da idade moderna, você vê que esse simples fato que eu mencionei já mostra o quanto é inviável você compreender essa sociedade como se fosse um poder secreto que está controlando a história humana. É claro que existem dentro das mesmas indivíduo que tem a presunção de ser, por assim dizer, os administradores do Cosmos, não só na maçonaria muito lugar tem isso, né, mas quando você vê o pouco controle que a Maçonaria tem sobre a sua própria história, ao ponto de um grão-mestre maçônico tem que pular que nem um cabrito para tentar se orientar no meio da alto mistificação, ele, mas como a sociedade que conhece tão mal a sua própria história pode dirigir a história humana, né, então quer dizer a história do poder secreto, o poder secreto não existe, existe uma presunção de poder secreto, mas é muitos gostaria, mas isso de fato não acontece. É só Deus dirige o curso da história humana, ninguém mais, quer dizer, não adianta você tentar hipertrofiar o poder, a imagem desses indivíduo, imaginar que eles estão realmente controlando tudo, eu faço uma coisa ser secreta, não quer dizer que ela tem poder.</p>

<p>De fato sobre o curso total dos acontecimentos, né, nem somente sobre uma parte dele, global e você, mais vezes, pessoal, cometendo erros e tropeçando e se dando muito mal do que conseguindo realizar os seus planos. O que acontece é que você tem que levar em conta que existe essa interferência, não, não imaginar que por ser secreta ela é a explicação do que tá acontecendo, é só mais um elemento do conjunto.</p>
<p>Eu sugerir o seguinte: que em vez de fazer esta maldita maneira de querer a explicação para tudo, o que nós temos que buscar mas é o conhecimento, eu saber, e não necessariamente a explicação. Admitir os fatos que você não compreende é você abrir-se para a realidade. Na verdade, desde o momento em que nascemos, nós estamos abertos para uma realidade que nós não compreendemos, e daí qual é o problema de não compreender? Significa não, não compreender significa que você não tem o domínio intelectual sobre o que está acontecendo, é importante também, não tem o domínio prático. Ou seja, você não é o senhor do processo, né, e você, na verdade, nem consegue aprender a forma do processo. Nós estamos acabando de ver que as tentativas de aprender a forma de processo são ilusórias.</p>
<p>Tá certo, e a verdadeira forma de instalação do ser humano na realidade é a abertura total e a confiança em Deus. Não tem outra coisa, quer dizer, você não vai achar um princípio explicativo mais abrangente e maior do que tem no evangelho. Vocês não vão passar disso, ninguém vai passar. Quando você vê as grandes presunções de domínio ideológico domínio intelectual da realidade</p>

<p>Augusto conte, etc, está na hora de saber que a verdadeira verdadeiro trato do ser humano com a realidade não consiste em domínio intelectual da situação. Aceitação da realidade. Porque eu deveria ficar aterrorizado porque o universo está sobre o meu controle? Se estiver sob meu controle, que estaria aterrorizar? Algumas perguntas aqui.</p>
<p>Aqui, Fábio Chaves pergunta: "Muito obrigado pela aula sobre as doze camadas. Na época, infelizmente, sua apostila fiz uma pergunta sobre as aplicações da teoria para literatura que agora repito. Um escritor que tratou da Ascensão nas camadas superiores, especificamente a décima segunda, não foi uma festa perfeitamente? Foi essa uma das ideias dele? Se dar também imediato também, um romance 'O Fio da Navalha' gira em torno de um personagem que estava cansado e da incapacidade completa de todos em volta de compreenderam o que se passa com ele. Muito."</p>
<p>"Diário de um Parque da Aldeia" é indivíduo cuja vida inteira é presidido pela pela providência divina. Também não ent

<p>Também não entende, mas muito menos os outros entendem. Outros exemplos eu acho que esta de aplicação das doze camadas como instrumento para descrição dos personagens literário é perfeito. Perfeito. Eu nunca tentei isso, mas eu acho que é perfeitamente factível. E se alguém, como você Fábio, quiser desenvolver algum estudo sistemático nesse sentido, você fará uma grande contribuição.</p>
<p>Porque evidente que essas duas camadas existem no ser humano real também vai ter que ser refletido de alguma maneira de ficção que são os modelos das vidas possíveis, né?</p>