<h1>Manis Friedman</h1>

<p>Não é apenas um estereótipo. Eu viajei por todo mundo e onde quer que eu vá, os judeus sempre são identificados como uma sessão mais sortuda das pessoas que residem nos países. Durante os últimos dois mil anos, os judeus foram expulsos ou separados de quase todos os países do mundo, mas, repetidas vezes, eles conseguiram se recuperar, começar do zero e construir uma significativa fortuna em novas terras. Apesar de terem sido expulsos novamente, repetem o processo desde o início e voltam a ser bem-sucedidos. </p>

<p>Meu povo teve mais conhecimento de como administrar o dinheiro do que outras pessoas da terra. A sabedoria desses conselhos eternos que te revelarei passaram de geração em geração e permite que inúmeras pessoas construam fortuna financeira e prosperidade pessoal. Se você seguir esses simples conselhos, você ganhará o controle de suas próprias finanças e provavelmente será capaz de acumular milhões e milhões de dólares. Estes conselhos não são apenas sobre dinheiro, mas também sobre sua própria disciplina e prova de amor entre você e sua família. Enquanto vamos trazer essas dicas de sabedoria do povo Judeu, você verá que isso pode se aplicar a qualquer religião ou nível econômico. Este é o sistema financeiro mais antigo da história e o único que sobreviveu no tempo. Vamos lá! </p>

<p>Preencha o vazio sem esvaziar os bolsos. Quantas vezes compramos coisas que precisamos ou roupas que nunca usaremos, simplesmente porque sentimos uma urgência imperativa de fazer e não somos capazes de resistir. Quando fazemos essas coisas, na verdade, estamos preenchendo um vazio em nossas vidas com dívidas. É um processo lento, mas seguro, de autodestruição e isso nos levará passo a passo a entrar em total depressão e pobreza. O que devemos aprender é tratar e responder a esse tipo de situação em uma forma que de luz e prosperidade e as nossas vidas e não mais caos. Vamos imaginar por um momento que existe dois seres que vivem dentro de nós. </p>

<p>A primeira é a besta. Esta é a parte da sua alma que controla seus apetites, sua ganância, sua fome por bens materiais, só a necessidade de satisfação instantânea. Ela vive no fundo de nosso estômago e deseja engordar. Quanto mais gorda ela fica, mas nos atrasa. Seu plano é trazer caos para sua vida. Na realidade, a besta foi criada para servir como um contrapeso de equilíbrio do seu segundo ser interior, seu anjo. Seu anjo sabe as coisas certas para se fazer, mas às vezes a besta leva a melhor sobre ele. O verdadeiro problema é que você está alimentando a besta. Você está permitindo que ela corra livremente e vença seu anjo. E isso se reflete em sua vida financeira, é a razão pela qual o seu salário vem e se vai e torna a prosperidade impossível.</p>

<p>Agora vamos fazer algo diferente. Em vez de alimentar a besta, o custo do seu futuro, vamos tentar controlar a besta e colocá-la para trabalhar para você, não contra você. A primeira coisa que você deve fazer é olhar para si mesmo e entender que você é igualmente responsável pelos seus sucessos assim como pelos seus fracassos.</p>

<p>Da próxima vez que você pensar em comprar algo caro, eu quero que você saia da loja e pense na compra por uma semana. Ignore a besta que o torna atraente ter satisfação instantânea. Acredito que a verdadeira definição de riqueza é amar o que você tem ao invés do que você não tem. Veja sua riqueza do ponto de vista de Deus.</p>

<p>Ao longo dos anos, diferentes grupos se autodenominam vítimas. Alguns deles vieram de guerras e massacres, mas os judeus que foram vítimas ao longo da história não se vêem como vítimas. Nós nos vemos como Sobreviventes. A diferença entre Sobreviventes e vítimas é que os Sobreviventes continuam com suas vidas após a tragédia, enquanto as vítimas continuam a lamentar sua própria desgraça. Como entendemos, tudo está na Bíblia por uma razão, para nos ensinar uma lição. Deste modo, vemos como Deus atribui seu tempo para trabalhar e mantém seu sétimo dia para descansar. O conceito de orçamento foi criado por Deus para nos dar uma vida de prosperidade no mundo que ele criou para nós. Então, devemos aprender a fazer um orçamento para imitar Deus em nossa vida financeira. </p>

<p>Aprendendo essas verdades eternas não só preparará a sua família para um futuro melhor e mudará a história da sua família para sempre, mas também dará autoconfiança que precisa. Você vai acordar todos os dias ansioso por estar vivo e por saber que hoje é melhor que ontem e amanhã será muito melhor que hoje. Você estará conectado com a corrente da prosperidade. Até agora, seu dinheiro lhe disse o que fazer e como trabalhar. Agora você tem que dar a volta. Você tem que aprender a dizer ao seu dinheiro o que fazer e como trabalhar para você. Sua esposa, sua vida, o jogo financeiro é um esporte de equipe.</p>

<p>Deus estabeleceu uma aliança com Noé depois do dilúvio. E então estabeleceu uma aliança com Abraão. Uma aliança é um contrato entre duas partes. Para poder prosperar, você deve estabelecer o que eu chamo de aliança com sua família. A aliança mostrará seu compromisso com sua família e seu futuro juntos, e eles devem fazer o mesmo compromisso com você. Comece por discutir honestamente onde você está atualmente desde o ponto financeiro e onde você quer chegar. Fale sobre quais coisas você vai sacrificar e pergunte a sua família o que eles vão sacrificar para ter um futuro mais próspero. Para seguir em frente em sua vida financeira, um requisito mínimo é que todos devem estar na mesma página, na mesma sintonia, porque você e sua família estão literalmente no mesmo barco financeiro assim como Noé e sua família estiveram na arca.</p>

<p>Como rabino, passo muitas horas aconselhando pessoas casadas. E em cada caso, gosto de falar com o casal, não só sobre compatibilidade e amor, mas também sobre sua relação com o dinheiro. Se você e seu parceiro não estão no mesmo canal financeiro, a chance de que seu casamento não dê certo não pode ser ignorada. Quando está casado, os problemas financeiros são a causa número um dos divórcios.</p>

<p>O dinheiro é energia. Fornece nossas necessidades básicas e nos dá escolhas e oportunidades. Quando você acumula riquezas, pode escolher se quer trabalhar ou quando quer trabalhar. Pode escolher ajudar uma instituição de caridade ou outro trabalho beneficente ao redor do mundo. Você também pode dar às próximas gerações mais oportunidades. Segundo a tradição Judaica, um ato de caridade tem a capacidade de mudar um decreto negativo do céu. A caridade não só significa melhorar o mundo e aqueles a seu redor, mas também a nós mesmos.</p>

<p>Este é o segredo de como o povo Judeu criou uma fronteira contra o caos, em parceria com Deus. Compartilhar cria um espaço em sua vida para mais bênçãos por vir. O dar cria um círculo sem fim: você ganha, você dá e depois ganha mais.</p>
